@base = http://localhost:8080
@accountNumber = 340365127009
@pin = 123456

### login (gets atmJwt)
# @name atmLogin
POST {{base}}/api/v1/atm/auth/login
Content-Type: application/json

{
  "accountNumber": "{{accountNumber}}",
  "pin": "{{pin}}"
}

> {%
    client.global.set("atmJwt", response.body.token);
%}

### hit balance many times quickly (after ~5 -> 429)
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}

###
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}

###
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}

###
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}

###
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}

###
GET {{base}}/api/v1/atm/me/balance
Authorization: Bearer {{atmJwt}}




@base = http://localhost:8080
@partnerApiKey = 15707253af2c2bc78bf3ba8425f41968374845a7bc5f55ed30c82d1cbb634fab

### spam this quickly -> 429
GET {{base}}/api/v1/partner/me/balance
X-API-Key: {{partnerApiKey}}
